db:
  full_url: "mysql+mysqldb://username:password@localhost/db_name"
  username: username
  password: password
  host: localhost
  db_name: db_name

kucoin:
  api_key: key
  api_secret: secret
  api_passphrase: password